FROM openedge:12.5.2

#WORKDIR /app

#COPY batchRunner.p ./batchRunner.p
#COPY batchRunner.pf ./batchRunner.pf
#COPY batchRunner.sh ./batchRunner.sh

#RUN chmod 755 /app/batchRunner.sh

ENTRYPOINT [ "/app/batchRunner.sh" ]